[general]
	#The Application ID of the Discord App to use. Replace this with your client id from the discord dashboard to change the name of the app
	applicationID = 1014225037458427985
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Minecraft is aan het laden"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[init.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[init.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is in het menu"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[main_menu.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[main_menu.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is op zoek naar een server"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[server_list.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[server_list.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is op zoek naar een Realm"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[realms_list.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[realms_list.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is aan het verbinden"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[join_game.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[join_game.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "%player% speelt Singleplayer"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[single_player.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[single_player.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "%player% speelt op de Vloedje SMP"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[multi_player.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[multi_player.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% speelt op een Realm"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord 

	[[realms.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[realms.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[generic]
	#The first line of text under the app name
	description = "Minecraft spelen"
	#The second line of text under the app name
	state = ""
	#The Asset ID/URL of the image to display as the large image
	largeImageKey = ["vloedje"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Speel mee survival.vloedje.nl!"
	#The Asset ID/URL of the image to display as the small image
	smallImageKey = []
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord 

	[[generic.buttons]]
		label = "Discord"
		url = "https://vloedje.nl/discord"

	[[generic.buttons]]
		label = "Whitelist"
		url = "https://vloedje.nl/whitelist"


[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

[dimension_overrides]
	enabled = false

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = ["vloedje"]
		largeImageText = "In the Overworld"
		smallImageKey = ["vloedje"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = ["vloedje"]
		largeImageText = "In the Nether"
		smallImageKey = ["vloedje"]
		smallImageText = "%mods% mods installed"
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = ["vloedje"]
		largeImageText = "In the End"
		smallImageKey = ["vloedje"]
		smallImageText = "%mods% mods installed"
		buttons = []


