name = "Vloedje 1.19"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e21417a6fe790b2b8f9bf2ebd97a298e762fb2ddab960c3e817ed48e052b51b9"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.23"
