name = "Vloedje SMP"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75b694e367516009ba052c7ef16bee7c262b2fa10f5eb40e1d856ffc85f60655"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2", "1.19.1", "1.19"]
