name = "Vloedje SMP"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71660b3133dc730372319266636459991cab3a86e433e8221aff00f655434a87"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2", "1.19.1", "1.19"]
