name = "Vloedje SMP"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce3241982c71d60a2da0c71d98f42c0bf543859bc1a2e22c256092d1d0f70330"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2", "1.19.1", "1.19"]
