name = "Vloedje SMP Vulkan"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d586d0c01a75c22fa54c0c05418ab013b2adcfc2b7fc59a81d402af6d6174fe"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
