name = "Vloedje SMP Lite"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58ce276cc25da63d73b7dab3e286fed14a9115856ee60e682e393ae1022fbf69"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
