name = "Vloedje SMP Lite"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c01d64995fab5d1ad1cfd7887910fee0e9d973cb683dd5d5b8e588a0c383fce"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"
