name = "Vloedje SMP Content Creator"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4d3634fa8e0bfbd738ed553c467e0e9c9b2c04df1f27d0c5f3ba062b02a277f"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.25"
