name = "Vloedje SMP Content Creator"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6044666b2b86d4bd904893d3df9c767676c6a90678bd43d5918a94673d47d549"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.12"
