backgroundColor = -16777216
pressedBackgroundColor = 926762823
keyColor = 16777215
pressedKeyColor = 0
isEnabled = false
renderInGui = true
keyShadow = false
showMovement = true
showClick = true
showJump = true
cpsType = "ALWAYS"
displayFactor = 0.8
horizontalSlider = 20
verticalSlider = 85
