name = "Vloedje SMP Standard"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "822ce4d4cd9eb621f36fb6cea16bc3868330670c8731d0d39139d3cfc97ff587"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"

[options]
acceptable-game-versions = ["1.20.1"]
