name = "Vloedje SMP Standard"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38532dc96c6031f02aa57fc6f4a2b4543292f8a9c4dba129cee4033861e09293"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20.1"]
