name = "Vloedje SMP Standard"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e33ee722d753b5a99edd37ad61afa41d156b36c8cf2b91bba7d28534ac4681d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20"]
