name = "Vloedje SMP Standard"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e89e0be74588e0ca678070ac9df53a57a2afd57aab52f5ce4120d8b46eedfeb"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.5"

[options]
acceptable-game-versions = ["1.20.1"]
