name = "Vloedje SMP Standard"
author = "EEstar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d312588b9b0c9c19fe78a828b455f329477e8fab2ce99f67eb9f63e72e63860a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"

[options]
acceptable-game-versions = ["1.20.1"]
